import { ThemeProvider } from "@/components/theme-provider";
import { BackgroundBeams } from "@/components/aceternityui/background-beams";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { FloatingDockDemo } from "../components/ui/navbar/Navbar";
import "./globals.css";
import Template from "./template";

export const metadata: Metadata = {
  title: "JC DEV",
  description: "Generated by JC DEV",
};

const mn = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${mn.className} relative`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <main className="relative z-10">
              <Template>{children}</Template>
              <FloatingDockDemo />
            </main>
          </ThemeProvider>
          <BackgroundBeams className="absolute inset-0 z-0" />
        </body>
      </html>
    </>
  );
}
